In [13]:
import tensorflow as tf
import numpy as np
from tensorflow.contrib.learn.python.learn.datasets import base



In [3]:
flowers = {0:"setosa", 1: "versicolor", 2: "virginica"} 

training = "/home/student/Desktop/iris_training.csv"
test = "/home/student/Desktop/Iris_test.csv"
predict = "/home/student/Desktop/iris_predict.csv"
training_set = base.load_csv_with_header(filename = training, features_dtype = np.float32,target_dtype = np.int)

test_set = base.load_csv_with_header(filename = test, features_dtype = np.float32,target_dtype = np.int)
predict_set = base.load_csv_with_header(filename = predict, features_dtype = np.float32,target_dtype = np.int) 

print(test_set.data)
print(training_set.target)

Instructions for updating:
Use tf.data instead.
[[5.9 3.  4.2 1.5]
 [6.9 3.1 5.4 2.1]
 [5.1 3.3 1.7 0.5]
 [6.  3.4 4.5 1.6]
 [5.5 2.5 4.  1.3]
 [6.2 2.9 4.3 1.3]
 [5.5 4.2 1.4 0.2]
 [6.3 2.8 5.1 1.5]
 [5.6 3.  4.1 1.3]
 [6.7 2.5 5.8 1.8]
 [7.1 3.  5.9 2.1]
 [4.3 3.  1.1 0.1]
 [5.6 2.8 4.9 2. ]
 [5.5 2.3 4.  1.3]
 [6.  2.2 4.  1. ]
 [5.1 3.5 1.4 0.2]
 [5.7 2.6 3.5 1. ]
 [4.8 3.4 1.9 0.2]
 [5.1 3.4 1.5 0.2]
 [5.7 2.5 5.  2. ]
 [5.4 3.4 1.7 0.2]
 [5.6 3.  4.5 1.5]
 [6.3 2.9 5.6 1.8]
 [6.3 2.5 4.9 1.5]
 [5.8 2.7 3.9 1.2]
 [6.1 3.  4.6 1.4]
 [5.2 4.1 1.5 0.1]
 [6.7 3.1 4.7 1.5]
 [6.7 3.3 5.7 2.5]
 [6.4 2.9 4.3 1.3]]
[2 1 2 0 0 0 0 2 1 0 1 1 0 0 2 1 2 2 2 0 2 2 0 2 2 0 1 2 1 1 1 1 1 2 2 2 2
 2 0 0 2 2 2 0 0 2 0 2 0 2 0 1 1 0 1 2 2 2 2 1 1 2 2 2 1 2 0 2 2 0 0 1 0 2
 2 0 1 1 1 2 0 1 1 1 2 0 1 1 1 0 2 1 0 0 2 0 0 2 1 0 0 1 0 1 0 0 0 0 1 0 2
 1 0 2 0 1 1 0 0 1]


In [4]:
features_name = "flower_features"
feature_columns = [tf.feature_column.numeric_column(features_name, shape =[4])]


In [5]:
classifier =tf.estimator.LinearClassifier(feature_columns = feature_columns, model_dir = "./Iris Model", n_classes =3)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': './Iris Model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fd847d77978>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [6]:
def input_fn(dataset):
    def _fn():
        features = {features_name: tf.constant(dataset.data)}
        label = tf.constant(dataset.target)
        return features, label
    return _fn


In [7]:
classifier.train(input_fn = input_fn(training_set), steps = 2000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./Iris Model/model.ckpt-51000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 51001 into ./Iris Model/model.ckpt.
INFO:tensorflow:loss = 4.396549, step = 51001
INFO:tensorflow:global_step/sec: 1411.21
INFO:tensorflow:loss = 4.394927, step = 51101 (0.072 sec)
INFO:tensorflow:global_step/sec: 2649.01
INFO:tensorflow:loss = 4.393301, step = 51201 (0.038 sec)
INFO:tensorflow:global_step/sec: 2638.87
INFO:tensorflow:loss = 4.3916826, step = 51301 (0.038 sec)
INFO:tensorflow:global_step/sec: 2614.4
INFO:tensorflow:loss = 4.390066, step = 51401 (0.038 sec)
INFO:tensorflow:global_step/sec: 2713.43
INFO:tensorflow:loss = 4.38846, step = 51501 (0.037 sec)
INFO:tensorflow:global_step/sec: 2833.36
INFO:tensorflow:loss = 4.3868594, s

In [8]:
accuracy_score = classifier.evaluate(input_fn = input_fn(test_set), steps = 2000)
print(accuracy_score)
print("the accuracy for this model is", accuracy_score['accuracy'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-07-03-00:13:36
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./Iris Model/model.ckpt-53000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [200/2000]
INFO:tensorflow:Evaluation [400/2000]
INFO:tensorflow:Evaluation [600/2000]
INFO:tensorflow:Evaluation [800/2000]
INFO:tensorflow:Evaluation [1000/2000]
INFO:tensorflow:Evaluation [1200/2000]
INFO:tensorflow:Evaluation [1400/2000]
INFO:tensorflow:Evaluation [1600/2000]
INFO:tensorflow:Evaluation [1800/2000]
INFO:tensorflow:Evaluation [2000/2000]
INFO:tensorflow:Finished evaluation at 2018-07-03-00:13:37
INFO:tensorflow:Saving dict for global step 53000: accuracy = 0.96666664, average_loss = 0.070599474, global_step = 53000, loss = 2.117984
{'accuracy': 0.96666664, 'average_loss': 0.070599474, 'loss': 2.117984, 'global_step': 53000

In [9]:
predict_x = {
    'SepalLength':[5.1,5.9,6,9], 
    'SepalWidth':[3.3,3.0,3.1],
    'PetalLength':[1.7,4.2,5.4],
    'PetalWidth':[0.5,1,5,2.1],
}

In [12]:
predictor = classifier.predict(input_fn = input_fn(predict_set))
print(predictor)

i = 0
for p in predictor:
    if i < 3:
        print("Features: ", p['logits'])
        print("Guesstimate: ", flowers[int(p['class_ids'])])
        i += 1
    else:
        break

<generator object Estimator.predict at 0x7fd844126728>
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./Iris Model/model.ckpt-53000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Features:  [ 25.407497  18.05625  -22.273615]
Guesstimate:  setosa
Features:  [-12.797027    1.1738148   7.683405 ]
Guesstimate:  virginica
Features:  [-2.0075197  6.560093  -1.3212042]
Guesstimate:  versicolor
